### ISSUE TITLE
Garrison Resources show as red when you have enough to purchase an item

### ISSUE THREAD

**Issue by MeatyChunks** [TekNoLogic/GnomishVendorShrinker#34]
Only minor, but the currency column shows as red, even if you have enough to buy the item. Using 6.0.0.17-Beta.

![clipboard02](https://cloud.githubusercontent.com/assets/6160351/6488969/e06988b0-c292-11e4-855d-c3a4d7c481e9.jpg)

Cheers

**Comment by tekkub** [comment]
Works for me! 

![image](https://cloud.githubusercontent.com/assets/706/6548325/0c6689de-c5ba-11e4-8e8f-b5fdb24e242c.png)

**Comment by Talyrius** [comment]
Yeah, it works for me as well. However, it does show as red when something is purchasable with items located in your bank. You don't have to have them on you anymore. :smirk:

**Comment by tekkub** [comment]
That's fixed in 13c4b167 and will go out in the next release.

**Comment by Talyrius** [comment]
Nice. I hadn't seen that commit. :satisfied:
