### ISSUE TITLE
Unlearned recipes that make already-learned toys show as learned

### ISSUE THREAD

**Issue by flatluigi** [TekNoLogic/GnomishVendorShrinker#37]
If you're at a vendor that sells recipes that make toys that you've already got in your toybox, the "already known" text in the toy's description makes the addon think you've already learned the recipe, too. Easiest example is the Draenor engineering trainer that sells recipes for the daily secret cooldown item; the "World Shrinker" and "Personal Hologram" toys are both affected by this bug.

**Comment by tekkub** [comment]
Sadly this isn't something I can easily fix.  I have to scan the tooltip for that "Already known" string, and the way recipe tooltips work has long been riddled with potholes.

Now then, if Blizzy would give us an API to query if a recipe is learned, then I could fix this very easily.
