### ISSUE TITLE
GetAuctionItemClasses() returns 'nil' value for legion pre-patch

### ISSUE THREAD

**Issue by Zerovii** [TekNoLogic/GnomishVendorShrinker#39]
When trying to open a vendor window on 7.0.3, this error pops up. It's for line 239:
local _, _, _, _, _, _, RECIPE = GetAuctionItemClasses()
I think they removed/broke the API call and I can't seem to see any replacement call for it.

**Comment by Talyrius** [comment]
That line can be replaced with:
```lua
local RECIPE = GetItemClassInfo(LE_ITEM_CLASS_RECIPE)
```

**Comment by Zerovii** [comment]
Thank you, i thought i found the right call in the new auctiondata lua but
i see i was close but not quite at the right one. My friend appreciates it
