### ISSUE TITLE
Problems @ WoWInterface & WowAce

### ISSUE THREAD

**Issue by Talyrius** [TekNoLogic/GnomishVendorShrinker#42]
- The previous release was mistakenly reuploaded to [WoWInterface](http://www.wowinterface.com/downloads/info14425.html) and labeled as the new one.
- GnomishVendorShrinker's development stage at [WowAce](https://www.wowace.com/addons/gnomishvendorshrinker/) is still marked as abandoned, so it's not being syndicated to Curse.

**Comment by tekkub** [comment]
Derp.  Fixed.
