### ISSUE TITLE
Version 7.0.0.20-Beta Vendor List is Blank

### ISSUE THREAD

**Issue by Tetsemi** [TekNoLogic/GnomishVendorShrinker#43]
All addons disabled except GnomishVendorShrinker, no errors caught, but the vendor list on all vendors is now blank. I can sell to the vendor without an issue, but can not choose anything as the window is blank.

This is for normal vendors, tradeskill vendors that sell recipes, and tradeskill vendors that sell supplies only.

**Comment by xtoq** [comment]
Reverting to beta .19 fixed this issue for me.

**Comment by VaporAPX** [comment]
Yep, same issue as stated above. Using .19 again.

**Comment by tekkub** [comment]
Just released a fix
