### ISSUE TITLE
a error when i logged in my alt after updated to latest version of this

### ISSUE THREAD

**Issue by Entranze** [TekNoLogic/GnomishVendorShrinker#45]
Message: ...dOns\GnomishVendorShrinker\GnomishVendorShrinker.lua:252: attempt to call global 'GetAuctionItemClasses' (a nil value)
Time: 10/08/16 02:12:54
Count: 1
Stack: ...dOns\GnomishVendorShrinker\GnomishVendorShrinker.lua:252: in main chunk

Locals: myname = "GnomishVendorShrinker"
ns = <table> {
 knowns = <table> {
 }
 GSC = <function> defined @Interface\AddOns\GnomishVendorShrinker\tekFunks\gsc.lua:4
 IHASCAT = true
}
ItemSearch = <table> {
 RegisterTypedSearch = <function> defined @Interface\AddOns\GnomishVendorShrinker\LibItemSearch-1.0.lua:110
 GetTypedSearches = <function> defined @Interface\AddOns\GnomishVendorShrinker\LibItemSearch-1.0.lua:114
 FindUnionSearch = <function> defined @Interface\AddOns\GnomishVendorShrinker\LibItemSearch-1.0.lua:46
 Find = <function> defined @Interface\AddOns\GnomishVendorShrinker\LibItemSearch-1.0.lua:27
 FindNegatableSearch = <function> defined @Interface\AddOns\GnomishVendorShrinker\LibItemSearch-1.0.lua:82
 FindTypedSearch = <function> defined @Interface\AddOns\GnomishVendorShrinker\LibItemSearch-1.0.lua:122
 FindIntersectSearch = <function> defined @Interface\AddOns\GnomishVendorShrinker\LibItemSearch-1.0.lua:67
 Compare = <function> defined @Interface\AddOns\GnomishVendorShrinker\LibItemSearch-1.0.lua:142
 GetTypedSearch = <function> defined @Interface\AddOns\GnomishVendorShrinker\LibItemSearch-1.0.lua:118
}
NUMROWS = 14
ICONSIZE = 17
GAP = 4
SCROLLSTEP = 5
HONOR_POINTS = "[Honor Points]"
ARENA_POINTS = "[Arena Points]"
GVS = <unnamed> {
 0 = <userdata>
}
OnClick = <function> defined @Interface\AddOns\GnomishVendorShrinker\GnomishVendorShrinker.lua:25
PopoutOnClick = <function> defined @Interface\AddOns\GnomishVendorShrinker\GnomishVendorShrinker.lua:37
Purchase = <function> defined @Interface\AddOns\GnomishVendorShrinker\GnomishVendorShrinker.lua:52
BuyItem = <function> defined @Interface\AddOns\GnomishVendorShrinker\GnomishVendorShrinker.lua:66
PopoutSplitStack = <function> defined @Interface\AddOns\GnomishVendorShrinker\GnomishVendorShrinker.lua:77
OnEnter = <function> defined @Interface\AddOns\GnomishVendorShrinker\GnomishVendorShrinker.lua:82
OnLeave = <function> defined @Interface\AddOns\GnomishVendorShrinker\GnomishVendorShrinker.lua:88
GetCurencyCount = <function> defined @Interface\AddOns\GnomishVendorShrinker\GnomishVendorShrinker.lua:94
SetValue = <function> defined @Interface\AddOns\GnomishVendorShrinker\GnomishVendorShrinker.lua:102
GetAltCurrencyFrame = <function> defined @Interface\AddOns\GnomishVendorShrinker\GnomishVendorShrinker.lua:116
AddAltCurrency = <function> defined @Interface\AddOns\GnomishVendorShrinker\GnomishVendorShrinker.lua:142
ROWHEIGHT = 21
rows = <table> {
 1 = <unnamed> {
 }
 2 = <unnamed> {
 }
 3 = <unnamed> {
 }
 4 = <unnamed> {
 }
 5 = <unnamed> {
 }
 6 = <unnamed> {
 }
 7 = <unnamed> {
 }
 8 = <unnamed> {
 }
 9 = <unnamed> {
 }
 10 = <unnamed> {
 }
 11 = <unnamed> {
 }
 12 = <unnamed> {
 }
 13 = <unnamed> {
 }
 14 = <unnamed> {
 }
}
default_grad = <table> {
 1 = 0
 2 = 1
 3 = 0
 4 = 0.75
 5 = 0
 6 = 1
 7 = 0
 8 = 0
}
grads = <table> {
 2 = <table> {
 }
 3 = <table> {
 }
 1 = <table> {
 }
 4 = <table> {
 }
 7 = <table> {
 }
 red = <table> {
 }
}
(*temporary) = nil
(*temporary) = "attempt to call global 'GetAuctionItemClasses' (a nil value)"

**Comment by Talyrius** [comment]
That's not the newest version. Download the latest beta from [here](https://www.wowace.com/addons/gnomishvendorshrinker/files/).
