### ISSUE TITLE
BUG: Cannot buy certain items at Hallow's End pet vendor

### ISSUE THREAD

**Issue by xtoq** [TekNoLogic/GnomishVendorShrinker#47]
Steps to reproduce
-----

1. Visit Woim (pet vendor) in Undercity courtyard.
2. Be sure you have at least 5 Tricky Treats currency.
3. Try to buy one (1) of any of the items that cost 5 Tricky Treats (Perky Pug costumes or the pet treats) by either clicking the item (without modifiers) or by clicking the arrow to the right of the item and selecting "1".

Expected outcome
-----

- You should be able to buy a single item.

Actual outcome
-----

- I am unable to purchase the item, and receive the message: "You can't buy the specified quantity of that item." 

Additional information
-----

- Using version 7.0.0.21-Beta of GVS.
- No errors are thrown.
- When I disabled GVS, I can buy the items without issue.
- I have plenty of Tricky Treats to purchase my item.
- You can actually attempt to buy any quantity of items, none will be purchased regardless.
- I had no trouble buying items from the other Hallow's End vendors, at least for the items I could afford to test.

Please let me know if you need additional information!

**Comment by tekkub** [comment]
Silly barter items that pretend to be real "currency" *coughbitcoinscough*

Fixed!
