### ISSUE TITLE
(8.0.1) Item text blank at vendors

### ISSUE THREAD

**Issue by bradxeno** [TekNoLogic/GnomishVendorShrinker#54]
Patch 8.0.1 has broken GVS to where no text labels show for most items. No errors thrown.

**Comment by neksudm** [comment]
@bradxeno replace MerchantItem.lua with the one in attached archive. I fixed it partly(text disappears if you drag merchant window). But i think we could live with this, as apparently it will not be fixed ;)

[MerchantItem.zip](https://github.com/TekNoLogic/GnomishVendorShrinker/files/2214169/MerchantItem.zip)

**Comment by bradxeno** [comment]
Fix tested and verified, thanks!
